# Generated by Django 2.1.1 on 2020-07-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='desription',
            new_name='description',
        ),
    ]
